workflows:
  bluebay-ios:
    name: BlueBay Wallet iOS
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    working_directory: mobile
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
