workflows:
  bluebay-ios:
    name: BlueBay Wallet iOS
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    working_directory: mobile
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign --export-method=ad-hoc
    artifacts:
      - build/ios/ipa/*.ipa
